import {
  AlertTriangle,
  FileText,
  Globe2,
  Layers3,
  MapPinned,
  Monitor,
  Route,
  Target,
  type LucideIcon,
} from "lucide-react";
import type { ScreenFamilySpec, SurfaceConfig, WorkspaceMode } from "./types";

export const T = {
  referenceBlue: "var(--geometry-reference-blue)",
  activeAmber: "var(--geometry-active-amber)",
  neutralMuted: "var(--geometry-neutral-muted)",
  panelBg: "var(--surface-panel)",
  panelBorder: "var(--color-panel-border)",
  alert: "var(--accent-alert)",
  verified: "var(--accent-verified)",
} as const;

export const AUXILIARY_RAIL_ICONS: LucideIcon[] = [MapPinned, AlertTriangle, Route, FileText, Layers3];

export const SCREEN_FAMILY_SPECS: Array<ScreenFamilySpec & { Icon: LucideIcon }> = [
  {
    id: "flat-map",
    name: "Flat Map",
    shortName: "Map Core",
    role: "Truth surface",
    question: "Where is it?",
    view: "2D",
    geometryBehavior: "BBox truth",
    selectionPersistence: "strong",
    compareRole: "strong",
    behaviorSummary: "Point, line, and polygon truth driven by bbox fit and shared dossier state.",
    shellTemplate: "map",
    detailMode: "persistent-dossier",
    topBarVariant: "map-scope",
    toolRailVariant: "full-index",
    sceneDominance: "medium",
    Icon: MapPinned,
  },
  {
    id: "eo-overlay",
    name: "EO Overlay",
    shortName: "EO Overlay",
    role: "Exploitation surface",
    question: "What do we see?",
    view: "Sensor overlay",
    geometryBehavior: "Directional annotation",
    selectionPersistence: "strong",
    compareRole: "medium",
    behaviorSummary: "Overhead exploitation with aimpoints, markup, directional cues, and measured context.",
    shellTemplate: "scene",
    detailMode: "floating-intel-card",
    topBarVariant: "tasking",
    toolRailVariant: "thin-instruments",
    sceneDominance: "maximum",
    Icon: Target,
  },
  {
    id: "site-3d",
    name: "Site 3D",
    shortName: "Site 3D",
    role: "Local context surface",
    question: "What is happening locally?",
    view: "Oblique 3D",
    geometryBehavior: "Site-focused",
    selectionPersistence: "strong",
    compareRole: "medium",
    behaviorSummary: "Local oblique surface for selected-site framing and task-asset context.",
    shellTemplate: "scene",
    detailMode: "floating-intel-card",
    topBarVariant: "tasking",
    toolRailVariant: "thin-instruments",
    sceneDominance: "maximum",
    Icon: Globe2,
  },
  {
    id: "theater-3d",
    name: "Theater 3D",
    shortName: "Theater 3D",
    role: "Mission geometry surface",
    question: "How does it relate operationally?",
    view: "3D operational",
    geometryBehavior: "Rings, routes, vectors",
    selectionPersistence: "strong",
    compareRole: "strong",
    behaviorSummary: "Mission geometry surface for rings, route vectors, and tasking relationships.",
    shellTemplate: "scene",
    detailMode: "floating-intel-card",
    topBarVariant: "tasking",
    toolRailVariant: "thin-instruments",
    sceneDominance: "maximum",
    Icon: Route,
  },
  {
    id: "ops-wall",
    name: "Ops Wall",
    shortName: "Ops Wall",
    role: "Supervisory surface",
    question: "What is happening overall?",
    view: "Dashboard",
    geometryBehavior: "Summary aggregation",
    selectionPersistence: "strong",
    compareRole: "summary",
    behaviorSummary: "Supervisory surface for mission clocks, queue panels, and command monitoring.",
    shellTemplate: "ops-wall",
    detailMode: "contextual-modules",
    topBarVariant: "command-wall",
    toolRailVariant: "wall-modules",
    sceneDominance: "high",
    Icon: Monitor,
  },
];

export const SCREEN_FAMILY_BY_ID = Object.fromEntries(
  SCREEN_FAMILY_SPECS.map((spec) => [spec.id, spec])
) as Record<WorkspaceMode, (typeof SCREEN_FAMILY_SPECS)[number]>;

export const SURFACE_CONFIG_BY_MODE: Record<WorkspaceMode, SurfaceConfig> = {
  "flat-map": {
    mode: "flat-map",
    lighting: "neutral",
    camera: "orthographic",
    gridVisible: true,
    groundPlaneVisible: false,
    annotationDensity: "medium",
    overlays: ["bbox", "reference-grid", "selection-ring"],
    backgroundVar: "var(--mode-flat-background)",
  },
  "eo-overlay": {
    mode: "eo-overlay",
    lighting: "cold",
    camera: "top-down-tilt",
    gridVisible: true,
    groundPlaneVisible: false,
    annotationDensity: "high",
    overlays: ["scan-grid", "measurement-guides", "aimpoint-boxes"],
    backgroundVar: "var(--mode-eo-background)",
  },
  "site-3d": {
    mode: "site-3d",
    lighting: "spot",
    camera: "fixed-oblique",
    gridVisible: true,
    groundPlaneVisible: true,
    annotationDensity: "medium",
    overlays: ["ground-plane", "local-frame", "reference-markers"],
    backgroundVar: "var(--mode-site-background)",
  },
  "theater-3d": {
    mode: "theater-3d",
    lighting: "radial",
    camera: "elevated-orbital",
    gridVisible: true,
    groundPlaneVisible: true,
    annotationDensity: "medium",
    overlays: ["ring-stack", "vector-suite", "scale-proof"],
    backgroundVar: "var(--mode-theater-background)",
  },
  "ops-wall": {
    mode: "ops-wall",
    lighting: "flat",
    camera: "orthographic",
    gridVisible: true,
    groundPlaneVisible: false,
    annotationDensity: "high",
    overlays: ["monitor-grid", "mission-geometry", "status-panels"],
    backgroundVar: "var(--mode-ops-background)",
  },
};

export const LAYERS = [
  { id: "zones", label: "Zones" },
  { id: "routes", label: "Routes" },
  { id: "incidents", label: "Incidents" },
  { id: "sites", label: "Sites" },
] as const;

export const WORKSPACE_INVARIANTS = ["Selection", "Compare", "BBox", "Dossier"] as const;
